import type { Subject } from "@/types/academic";

export const cloudComputingSyllabus: Subject = {
  id: "cloud-computing",
  name: "Cloud Computing",
  semesterId: "semester-3",
  modules: [
    {
      id: "cloud-computing-module-1",
      title: "Module 1: Introduction to Cloud Computing",
      description:
        "Fundamentals of cloud computing, distributed computing evolution, characteristics, opportunities and challenges.",
      estimatedStudyTimeMinutes: 300,
      difficulty: "easy",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "cc-m1-t1",
          title: "History of Centralized and Distributed Computing",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "cc-m1-t1-s1",
              title: "Centralized Computing",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t1-s2",
              title: "Distributed Computing",
              status: "not-started",
              resources: [],
            },
          ],
        },

        {
          id: "cc-m1-t2",
          title: "Overview of Distributed Computing",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "cc-m1-t2-s1",
              title: "Cluster Computing",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t2-s2",
              title: "Grid Computing",
              status: "not-started",
              resources: [],
            },
          ],
        },

        {
          id: "cc-m1-t3",
          title: "Technologies for Network-Based Systems",
          status: "not-started",
          difficulty: "medium",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "cc-m1-t3-s1",
              title: "System Models for Distributed Computing",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t3-s2",
              title: "System Models for Cloud Computing",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t3-s3",
              title: "Software Environments",
              status: "not-started",
              resources: [],
            },
          ],
        },

        {
          id: "cc-m1-t4",
          title: "Cloud Computing Fundamentals",
          status: "not-started",
          difficulty: "easy",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "cc-m1-t4-s1",
              title: "Definition of Cloud Computing",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t4-s2",
              title: "Components of Cloud Computing",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t4-s3",
              title: "Characteristics / Features",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t4-s4",
              title: "Cloud Computing vs On-Premise System",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t4-s5",
              title: "Evolution of Cloud Computing",
              status: "not-started",
              resources: [],
            },
          ],
        },

        {
          id: "cc-m1-t5",
          title: "Cloud Opportunities and Challenges",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "cc-m1-t5-s1",
              title: "Advantages of Cloud Computing",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t5-s2",
              title: "Disadvantages of Cloud Computing",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t5-s3",
              title: "Benefits of Cloud Computing",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m1-t5-s4",
              title: "Risks in Cloud Computing",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "cloud-computing-module-2",
      title: "Module 2: Virtualization",
      description:
        "Introduction to virtualization, types of virtualization and the role of hypervisors in cloud computing.",
      estimatedStudyTimeMinutes: 300,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "cc-m2-t1",
          title: "Introduction to Virtualization",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "cc-m2-t1-s1",
              title: "Introduction to Virtualization",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m2-t2",
          title: "Types of Virtualization",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 75,
          subtopics: [
            {
              id: "cc-m2-t2-s1",
              title: "Server Virtualization",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m2-t2-s2",
              title: "Desktop Virtualization",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m2-t2-s3",
              title: "Application Virtualization",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m2-t2-s4",
              title: "Operating System Virtualization",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m2-t3",
          title: "I/O Virtualization",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "cc-m2-t3-s1",
              title: "Input / Output Virtualization",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m2-t4",
          title: "Storage, Network and Memory Virtualization",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "cc-m2-t4-s1",
              title: "Storage Virtualization",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m2-t4-s2",
              title: "Network Virtualization",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m2-t4-s3",
              title: "Memory Virtualization",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m2-t5",
          title: "Hypervisors and Cloud Computing",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "cc-m2-t5-s1",
              title: "Hypervisors",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m2-t5-s2",
              title: "Virtualization and Cloud Computing",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "cloud-computing-module-3",
      title: "Module 3: Cloud Architecture, Services, and Storage",
      description:
        "Cloud architecture, deployment models, service models and cloud storage.",
      estimatedStudyTimeMinutes: 360,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "cc-m3-t1",
          title: "Cloud Architecture Design",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 75,
          subtopics: [
            {
              id: "cc-m3-t1-s1",
              title: "Cloud Architecture Design",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t1-s2",
              title: "NIST Reference Architecture",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m3-t2",
          title: "Cloud Deployment Models",
          status: "not-started",
          difficulty: "easy",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "cc-m3-t2-s1",
              title: "Public Cloud",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t2-s2",
              title: "Private Cloud",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t2-s3",
              title: "Hybrid Cloud",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t2-s4",
              title: "Community Cloud",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m3-t3",
          title: "Cloud Service Models",
          status: "not-started",
          difficulty: "easy",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "cc-m3-t3-s1",
              title: "Infrastructure as a Service (IaaS)",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t3-s2",
              title: "Platform as a Service (PaaS)",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t3-s3",
              title: "Software as a Service (SaaS)",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m3-t4",
          title: "Architecture Design Challenges",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "cc-m3-t4-s1",
              title: "Scalability",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t4-s2",
              title: "Availability",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t4-s3",
              title: "Reliability",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m3-t5",
          title: "Storage as a Service",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "cc-m3-t5-s1",
              title: "Storage as a Service (STaaS)",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t5-s2",
              title: "Advantages of Cloud Storage",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m3-t5-s3",
              title: "Cloud Storage Providers",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "cloud-computing-module-4",
      title: "Module 4: Resource Management in Cloud",
      description:
        "Cloud resource provisioning, management and identity access management.",
      estimatedStudyTimeMinutes: 300,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "cc-m4-t1",
          title: "InterCloud Resource Management",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "cc-m4-t1-s1",
              title: "InterCloud Resource Management",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m4-t2",
          title: "Resource Provisioning",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "cc-m4-t2-s1",
              title: "Resource Provisioning",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m4-t2-s2",
              title: "Resource Provisioning Methods",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m4-t3",
          title: "Global Exchange of Cloud Resources",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "cc-m4-t3-s1",
              title: "Global Exchange of Cloud Resources",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m4-t4",
          title: "Identity and Access Management",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "cc-m4-t4-s1",
              title: "Identity and Access Management (IAM)",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m4-t4-s2",
              title: "Security Assertion Markup Language (SAML)",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "cloud-computing-module-5",
      title: "Module 5: Security in Cloud",
      description:
        "Cloud security concepts, governance, standards and challenges.",
      estimatedStudyTimeMinutes: 300,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "cc-m5-t1",
          title: "Security Overview",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "cc-m5-t1-s1",
              title: "Introduction to Cloud Security",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m5-t1-s2",
              title: "Need for Cloud Security",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m5-t2",
          title: "Cloud Security Challenges",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "cc-m5-t2-s1",
              title: "Data Security",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m5-t2-s2",
              title: "Privacy",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m5-t2-s3",
              title: "Compliance",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m5-t2-s4",
              title: "Availability",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m5-t3",
          title: "Security Governance",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 75,
          subtopics: [
            {
              id: "cc-m5-t3-s1",
              title: "Security Policies",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m5-t3-s2",
              title: "Risk Management",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m5-t3-s3",
              title: "Compliance Management",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "cc-m5-t4",
          title: "Security Standards",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "cc-m5-t4-s1",
              title: "ISO/IEC 27001",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m5-t4-s2",
              title: "CSA Standards",
              status: "not-started",
              resources: [],
            },
            {
              id: "cc-m5-t4-s3",
              title: "NIST Security Standards",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
  ],
};