import type { Subject } from "@/types/academic";

export const computerArchitectureSyllabus: Subject = {
  id: "computer-architecture",
  name: "Computer Architecture",
  semesterId: "semester-3",
  modules: [
    {
      id: "computer-architecture-module-1",
      title: "Module 1: Introduction",
      description: "Overview of Computer Architecture & Organization",
      estimatedStudyTimeMinutes: 480,
      difficulty: "medium",
      marksWeightage: "15%",
      priority: "high",
      practice: [],
      topics: [
        {
          id: "ca-m1-t1",
          title: "Algorithms for Binary Multiplication and Division",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m1-t1-s1",
              title: "Binary Multiplication Algorithm",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t1-s2",
              title: "Binary Division Algorithm",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m1-t2",
          title: "Number Representation",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ca-m1-t2-s1",
              title: "Fixed-Point Number Representation",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t2-s2",
              title: "Floating-Point Number Representation",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m1-t3",
          title: "Functional Units of a Computer",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "ca-m1-t3-s1",
              title: "Input Unit",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t3-s2",
              title: "Memory Unit",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t3-s3",
              title: "Arithmetic Logic Unit (ALU)",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t3-s4",
              title: "Control Unit",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t3-s5",
              title: "Output Unit",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m1-t4",
          title: "Computer Architectures",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m1-t4-s1",
              title: "Von Neumann Architecture",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t4-s2",
              title: "Harvard Architecture",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t4-s3",
              title: "CISC Architecture",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t4-s4",
              title: "RISC Architecture",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m1-t5",
          title: "Processor Architecture",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ca-m1-t5-s1",
              title: "General Internal Architecture",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t5-s2",
              title: "Address Bus",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t5-s3",
              title: "Data Bus",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t5-s4",
              title: "Control Bus",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m1-t6",
          title: "Register Set",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ca-m1-t6-s1",
              title: "Status Register",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t6-s2",
              title: "Accumulator",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t6-s3",
              title: "Program Counter",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t6-s4",
              title: "Stack Pointer",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t6-s5",
              title: "General Purpose Registers",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m1-t7",
          title: "Processor Operation",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 150,
          subtopics: [
            {
              id: "ca-m1-t7-s1",
              title: "Instruction Cycle",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t7-s2",
              title: "Instruction Fetch",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t7-s3",
              title: "Instruction Decode",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t7-s4",
              title: "Instruction Execute",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t7-s5",
              title: "Timing Response",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t7-s6",
              title: "Instruction Sequencing and Execution",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m1-t7-s7",
              title: "Basic Data Path Concepts",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "computer-architecture-module-2",
      title: "Module 2: Introduction and Architecture of 8085",
      description: "Introduction to Microprocessors and 8085 Architecture",
      estimatedStudyTimeMinutes: 480,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ca-m2-t1",
          title: "Introduction to Microprocessors and Microcomputers",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "ca-m2-t1-s1",
              title: "Introduction to Microprocessors",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m2-t1-s2",
              title: "Introduction to Microcomputers",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m2-t2",
          title: "8085 Microprocessor",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m2-t2-s1",
              title: "8-bit Microprocessor",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m2-t2-s2",
              title: "8085 Pin Configuration",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m2-t3",
          title: "Internal Architecture and Operations",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m2-t3-s1",
              title: "Internal Architecture",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m2-t3-s2",
              title: "Instruction Execution",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m2-t3-s3",
              title: "Machine Cycle",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m2-t3-s4",
              title: "Timing Diagram Basics",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m2-t4",
          title: "Interrupts, Stack and Subroutines",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m2-t4-s1",
              title: "Interrupts",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m2-t4-s2",
              title: "Stack",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m2-t4-s3",
              title: "Subroutines",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m2-t5",
          title: "Data Transfer Schemes",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "ca-m2-t5-s1",
              title: "Programmed Data Transfer",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m2-t5-s2",
              title: "Interrupt Driven Transfer",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m2-t5-s3",
              title: "DMA Data Transfer",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "computer-architecture-module-3",
      title: "Module 3: Architecture and Peripherals for 8086",
      description: "8086 Architecture, Memory Segmentation and Peripheral Devices",
      estimatedStudyTimeMinutes: 480,
      difficulty: "hard",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ca-m3-t1",
          title: "Difference between 8085 and 8086",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "ca-m3-t1-s1",
              title: "Comparison of 8085 and 8086",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m3-t2",
          title: "8086 Architecture",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 150,
          subtopics: [
            {
              id: "ca-m3-t2-s1",
              title: "Block Diagram of 8086",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t2-s2",
              title: "8086 Family",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t2-s3",
              title: "Pin Configuration",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t2-s4",
              title: "Minimum Mode Operation",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t2-s5",
              title: "Maximum Mode Operation",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m3-t3",
          title: "Execution Unit and Memory Segmentation",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 150,
          subtopics: [
            {
              id: "ca-m3-t3-s1",
              title: "Merits of Memory Segmentation",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t3-s2",
              title: "Execution Unit",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t3-s3",
              title: "Register Organization",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t3-s4",
              title: "Addressing Modes",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t3-s5",
              title: "Instruction Set",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m3-t4",
          title: "Memory and Peripheral Devices",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m3-t4-s1",
              title: "Memory Segmentation",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t4-s2",
              title: "Memory Mapped I/O",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t4-s3",
              title: "Peripheral I/O",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t4-s4",
              title: "8255 Programmable Peripheral Interface",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t4-s5",
              title: "8253 Programmable Interval Timer",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t4-s6",
              title: "8257 DMA Controller",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t4-s7",
              title: "8259 Interrupt Controller",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m3-t4-s8",
              title: "8251 USART",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "computer-architecture-module-4",
      title: "Module 4: Architecture of 8051",
      description: "8051 Microcontroller Architecture and Organization",
      estimatedStudyTimeMinutes: 480,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ca-m4-t1",
          title: "Microprocessor vs Microcontroller",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "ca-m4-t1-s1",
              title: "Microprocessor",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t1-s2",
              title: "Microcontroller",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t1-s3",
              title: "Comparison between Microprocessor and Microcontroller",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m4-t2",
          title: "8051 Hardware",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ca-m4-t2-s1",
              title: "Oscillator",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t2-s2",
              title: "Clock Circuit",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m4-t3",
          title: "Registers and CPU Organization",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m4-t3-s1",
              title: "Program Counter (PC)",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t3-s2",
              title: "Data Pointer (DPTR)",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t3-s3",
              title: "Flags",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t3-s4",
              title: "Program Status Word (PSW)",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t3-s5",
              title: "CPU Registers",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m4-t4",
          title: "Memory Organization",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m4-t4-s1",
              title: "Internal RAM",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t4-s2",
              title: "RAM Organization",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t4-s3",
              title: "Special Function Registers (SFR)",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m4-t5",
          title: "I/O Ports and Peripheral Features",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 150,
          subtopics: [
            {
              id: "ca-m4-t5-s1",
              title: "I/O Pins",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t5-s2",
              title: "Ports and Port Circuits",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t5-s3",
              title: "Counters",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t5-s4",
              title: "Timers",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t5-s5",
              title: "Serial Transmission",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m4-t5-s6",
              title: "Interrupts",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "computer-architecture-module-5",
      title: "Module 5: Memory System",
      description: "Memory hierarchy, cache memory, virtual memory and input/output organization.",
      estimatedStudyTimeMinutes: 420,
      difficulty: "medium",
      marksWeightage: "15%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ca-m5-t1",
          title: "Types of Memory",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "ca-m5-t1-s1",
              title: "RAM",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t1-s2",
              title: "ROM",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m5-t2",
          title: "Memory Characteristics and Hierarchy",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ca-m5-t2-s1",
              title: "Memory Characteristics",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t2-s2",
              title: "Memory Hierarchy",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m5-t3",
          title: "Cache Memory",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m5-t3-s1",
              title: "Basics of Cache Memory",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t3-s2",
              title: "Cache Mapping Techniques",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t3-s3",
              title: "Improving Cache Performance",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m5-t4",
          title: "Virtual Memory",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ca-m5-t4-s1",
              title: "Overlay",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t4-s2",
              title: "Memory Management",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t4-s3",
              title: "Address Translation",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ca-m5-t5",
          title: "Input / Output Organization",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ca-m5-t5-s1",
              title: "Introduction",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t5-s2",
              title: "Synchronous vs Asynchronous I/O",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t5-s3",
              title: "Programmed I/O",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t5-s4",
              title: "Interrupt Driven I/O",
              status: "not-started",
              resources: [],
            },
            {
              id: "ca-m5-t5-s5",
              title: "Direct Memory Access (DMA)",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    }
      ],
};