import type { Subject } from "@/types/academic";

export const dataStructuresSyllabus: Subject = {
  id: "data-structures",
  name: "Data Structures",
  semesterId: "semester-3",
  modules: [
    {
      id: "data-structures-module-1",
      title: "Module 1: Introduction to Data Structures",
      description:
        "Fundamentals of data structures, abstract data types and complexity analysis.",
      estimatedStudyTimeMinutes: 240,
      difficulty: "easy",
      marksWeightage: "10%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ds-m1-t1",
          title: "Overview of Data Structures",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "ds-m1-t1-s1",
              title: "Introduction to Data Structures",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m1-t1-s2",
              title: "Classification of Data Structures",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m1-t2",
          title: "Abstract Data Types",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "ds-m1-t2-s1",
              title: "Concept of ADT",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m1-t2-s2",
              title: "Examples of ADTs",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m1-t3",
          title: "Complexity Analysis",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ds-m1-t3-s1",
              title: "Time Complexity",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m1-t3-s2",
              title: "Space Complexity",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m1-t3-s3",
              title: "Big-O Notation",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "data-structures-module-2",
      title: "Module 2: Arrays and Strings",
      description:
        "Introduction to arrays, multidimensional arrays and string handling.",
      estimatedStudyTimeMinutes: 360,
      difficulty: "easy",
      marksWeightage: "15%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ds-m2-t1",
          title: "Introduction to Arrays",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ds-m2-t1-s1",
              title: "Array Basics",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m2-t1-s2",
              title: "Array Operations",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m2-t2",
          title: "Multi-dimensional Arrays",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ds-m2-t2-s1",
              title: "2D Arrays",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m2-t2-s2",
              title: "Multi-dimensional Array Operations",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m2-t3",
          title: "Strings and String Handling Functions",
          status: "not-started",
          difficulty: "easy",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 180,
          subtopics: [
            {
              id: "ds-m2-t3-s1",
              title: "Strings",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m2-t3-s2",
              title: "String Handling Functions",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
    {
      id: "data-structures-module-3",
      title: "Module 3: Linked Lists",
      description:
        "Concepts, types and operations of linked lists.",
      estimatedStudyTimeMinutes: 480,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ds-m3-t1",
          title: "Introduction to Linked Lists",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ds-m3-t1-s1",
              title: "Need for Linked Lists",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t1-s2",
              title: "Structure of a Linked List",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m3-t2",
          title: "Types of Linked Lists",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 180,
          subtopics: [
            {
              id: "ds-m3-t2-s1",
              title: "Singly Linked List",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t2-s2",
              title: "Doubly Linked List",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t2-s3",
              title: "Circular Linked List",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m3-t3",
          title: "Operations on Linked Lists",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 210,
          subtopics: [
            {
              id: "ds-m3-t3-s1",
              title: "Insertion",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t3-s2",
              title: "Deletion",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t3-s3",
              title: "Traversal",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t3-s4",
              title: "Searching",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "data-structures-module-2",
      title: "Module 2: Arrays and Strings",
      description:
        "Introduction to arrays, multidimensional arrays and string handling.",
      estimatedStudyTimeMinutes: 360,
      difficulty: "easy",
      marksWeightage: "15%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ds-m2-t1",
          title: "Introduction to Arrays",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ds-m2-t1-s1",
              title: "Array Basics",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m2-t1-s2",
              title: "Array Operations",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m2-t2",
          title: "Multi-dimensional Arrays",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ds-m2-t2-s1",
              title: "2D Arrays",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m2-t2-s2",
              title: "Multi-dimensional Array Operations",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m2-t3",
          title: "Strings and String Handling Functions",
          status: "not-started",
          difficulty: "easy",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 180,
          subtopics: [
            {
              id: "ds-m2-t3-s1",
              title: "Strings",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m2-t3-s2",
              title: "String Handling Functions",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
    {
      id: "data-structures-module-3",
      title: "Module 3: Linked Lists",
      description:
        "Concepts, types and operations of linked lists.",
      estimatedStudyTimeMinutes: 480,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ds-m3-t1",
          title: "Introduction to Linked Lists",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ds-m3-t1-s1",
              title: "Need for Linked Lists",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t1-s2",
              title: "Structure of a Linked List",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m3-t2",
          title: "Types of Linked Lists",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 180,
          subtopics: [
            {
              id: "ds-m3-t2-s1",
              title: "Singly Linked List",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t2-s2",
              title: "Doubly Linked List",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t2-s3",
              title: "Circular Linked List",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m3-t3",
          title: "Operations on Linked Lists",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 210,
          subtopics: [
            {
              id: "ds-m3-t3-s1",
              title: "Insertion",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t3-s2",
              title: "Deletion",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t3-s3",
              title: "Traversal",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m3-t3-s4",
              title: "Searching",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "data-structures-module-6",
      title: "Module 6: Graphs",
      description:
        "Graph concepts, graph representations and graph traversal techniques.",
      estimatedStudyTimeMinutes: 240,
      difficulty: "medium",
      marksWeightage: "10%",
      priority: "high",
      practice: [],
      topics: [
        {
          id: "ds-m6-t1",
          title: "Basic Concepts and Terminologies",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "ds-m6-t1-s1",
              title: "Graph Terminologies",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m6-t1-s2",
              title: "Types of Graphs",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m6-t2",
          title: "Representation of Graphs",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ds-m6-t2-s1",
              title: "Adjacency Matrix",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m6-t2-s2",
              title: "Adjacency List",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m6-t3",
          title: "Graph Traversals",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "ds-m6-t3-s1",
              title: "Breadth First Search (BFS)",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m6-t3-s2",
              title: "Depth First Search (DFS)",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
    {
      id: "data-structures-module-7",
      title: "Module 7: Sorting and Searching",
      description:
        "Sorting and searching algorithms used in data structures.",
      estimatedStudyTimeMinutes: 240,
      difficulty: "medium",
      marksWeightage: "10%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "ds-m7-t1",
          title: "Sorting Algorithms",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ds-m7-t1-s1",
              title: "Bubble Sort",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m7-t1-s2",
              title: "Insertion Sort",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m7-t1-s3",
              title: "Quick Sort",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "ds-m7-t2",
          title: "Searching Algorithms",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "ds-m7-t2-s1",
              title: "Linear Search",
              status: "not-started",
              resources: [],
            },
            {
              id: "ds-m7-t2-s2",
              title: "Binary Search",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
  ],
};