import type { Subject } from "@/types/academic";

export const dbmsSyllabus: Subject = {
  id: "dbms",
  name: "Database Management System",
  semesterId: "semester-3",
  modules: [
    {
      id: "dbms-module-1",
      title: "Module 1: Introduction",
      description:
        "Introduction to DBMS, database design, ER diagrams and data models.",
      estimatedStudyTimeMinutes: 480,
      difficulty: "medium",
      marksWeightage: "25%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "dbms-m1-t1",
          title: "Introduction to DBMS",
          status: "not-started",
          difficulty: "easy",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "dbms-m1-t1-s1",
              title: "Concept of DBMS",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t1-s2",
              title: "Purpose of Database System",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t1-s3",
              title: "DBMS Architecture",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t1-s4",
              title: "Database System Applications",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t1-s5",
              title: "Database Users",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t1-s6",
              title: "Database Languages",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t1-s7",
              title: "File System vs DBMS",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t1-s8",
              title: "Levels of Abstraction",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t1-s9",
              title: "Database Administrator (DBA)",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m1-t2",
          title: "Database Design and ER Diagrams",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 180,
          subtopics: [
            {
              id: "dbms-m1-t2-s1",
              title: "Entity Type",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t2-s2",
              title: "Entity Set",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t2-s3",
              title: "Relationship Type",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t2-s4",
              title: "Relationship Set",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t2-s5",
              title: "Cardinality Ratio",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t2-s6",
              title: "Participation Constraints",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t2-s7",
              title: "Keys",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t2-s8",
              title: "Mapping",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t2-s9",
              title: "ER Model Design",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m1-t3",
          title: "Database Modeling",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "dbms-m1-t3-s1",
              title: "Types of Data Models",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t3-s2",
              title: "Phases of Database Modeling",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t3-s3",
              title: "Generalization",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t3-s4",
              title: "Specialization",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t3-s5",
              title: "Aggregation",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m1-t3-s6",
              title: "Extended Entity Relationship (EER) Model",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "dbms-module-2",
      title: "Module 2: DBMS Data Model",
      description:
        "Hierarchical, Network and Relational data models along with SQL fundamentals.",
      estimatedStudyTimeMinutes: 480,
      difficulty: "medium",
      marksWeightage: "25%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "dbms-m2-t1",
          title: "Hierarchical Model",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "dbms-m2-t1-s1",
              title: "Hierarchical Model Concepts",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t1-s2",
              title: "Data Definition",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t1-s3",
              title: "Data Manipulation",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t1-s4",
              title: "Implementation",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m2-t2",
          title: "Network Model",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "dbms-m2-t2-s1",
              title: "Network Model Definition",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t2-s2",
              title: "DBTG Set Constructs",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t2-s3",
              title: "Implementation",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m2-t3",
          title: "Relational Model",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "dbms-m2-t3-s1",
              title: "Relational Database",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t3-s2",
              title: "Relational Algebra",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t3-s3",
              title: "Relational Calculus",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t3-s4",
              title: "Tuple Calculus",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m2-t4",
          title: "Structured Query Language (SQL)",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 180,
          subtopics: [
            {
              id: "dbms-m2-t4-s1",
              title: "Overview of SQL",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s2",
              title: "Data Definition Language (DDL)",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s3",
              title: "Data Manipulation Language (DML)",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s4",
              title: "Data Control Language (DCL)",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s5",
              title: "Set Operations",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s6",
              title: "Aggregate Functions",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s7",
              title: "NULL Values",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s8",
              title: "Views in SQL",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s9",
              title: "Nested and Complex Queries",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s10",
              title: "Triggers",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m2-t4-s11",
              title: "PL/SQL",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "dbms-module-3",
      title: "Module 3: Schema Refinement and Normal Forms",
      description:
        "Schema refinement, functional dependencies and normalization techniques.",
      estimatedStudyTimeMinutes: 480,
      difficulty: "hard",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "dbms-m3-t1",
          title: "Introduction to Schema Refinement",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "dbms-m3-t1-s1",
              title: "Schema Refinement",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t1-s2",
              title: "Problems Caused by Redundancy",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t1-s3",
              title: "Decomposition",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t1-s4",
              title: "Problems Related to Decomposition",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m3-t2",
          title: "Functional Dependency",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "dbms-m3-t2-s1",
              title: "Functional Dependency",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t2-s2",
              title: "Closure of Functional Dependencies",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t2-s3",
              title: "Armstrong's Inference Rules",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m3-t3",
          title: "Normal Forms",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 180,
          subtopics: [
            {
              id: "dbms-m3-t3-s1",
              title: "Normalization Process",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t3-s2",
              title: "First Normal Form (1NF)",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t3-s3",
              title: "Second Normal Form (2NF)",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t3-s4",
              title: "Third Normal Form (3NF)",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t3-s5",
              title: "Boyce-Codd Normal Form (BCNF)",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t3-s6",
              title: "Multivalued Dependency",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m3-t3-s7",
              title: "Join Dependency",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "dbms-module-4",
      title: "Module 4: Transaction Management and Concurrency Control",
      description:
        "Transaction processing, concurrency control and database recovery techniques.",
      estimatedStudyTimeMinutes: 600,
      difficulty: "hard",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "dbms-m4-t1",
          title: "Transaction Basics",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 150,
          subtopics: [
            {
              id: "dbms-m4-t1-s1",
              title: "Introduction to Transactions",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t1-s2",
              title: "ACID Properties",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t1-s3",
              title: "Lifecycle of a Transaction",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t1-s4",
              title: "Need for Concurrency Control",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t1-s5",
              title: "Schedules",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t1-s6",
              title: "Serializability",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m4-t2",
          title: "Concurrency Control",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 180,
          subtopics: [
            {
              id: "dbms-m4-t2-s1",
              title: "Lock-Based Protocols",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t2-s2",
              title: "Timestamp-Based Protocols",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t2-s3",
              title: "Deadlock Handling",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m4-t3",
          title: "Recovery System",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 210,
          subtopics: [
            {
              id: "dbms-m4-t3-s1",
              title: "Failure Classification",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t3-s2",
              title: "Storage Structure",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t3-s3",
              title: "Recovery and Atomicity",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t3-s4",
              title: "Log-Based Recovery",
              status: "not-started",
              resources: [],
            },
            {
              id: "dbms-m4-t3-s5",
              title: "Shadow Paging",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "dbms-module-5",
      title: "Module 5: Recent Applications",
      description:
        "Modern database applications and emerging database technologies.",
      estimatedStudyTimeMinutes: 300,
      difficulty: "medium",
      marksWeightage: "10%",
      priority: "high",
      practice: [],
      topics: [
        {
          id: "dbms-m5-t1",
          title: "Mobile Databases",
          status: "not-started",
          difficulty: "easy",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "dbms-m5-t1-s1",
              title: "Introduction to Mobile Databases",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m5-t2",
          title: "Multimedia Databases",
          status: "not-started",
          difficulty: "medium",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "dbms-m5-t2-s1",
              title: "Introduction to Multimedia Databases",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m5-t3",
          title: "Geographical Information System (GIS)",
          status: "not-started",
          difficulty: "medium",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "dbms-m5-t3-s1",
              title: "Geographical Information System",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m5-t4",
          title: "Genome Data Management",
          status: "not-started",
          difficulty: "medium",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "dbms-m5-t4-s1",
              title: "Genome Data Management",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m5-t5",
          title: "Distributed Database",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "dbms-m5-t5-s1",
              title: "Distributed Database Concepts",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "dbms-m5-t6",
          title: "Object-Oriented Database",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "dbms-m5-t6-s1",
              title: "Object-Oriented Database Concepts",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
  ],
};