import type { Subject } from "@/types/academic";

export const frenchSyllabus: Subject = {
  id: "french",
  name: "French",
  semesterId: "semester-3",
  modules: [
    {
      id: "french-module-1",
      title: "Module 1",
      description: "Everyday life, environment and international culture.",
      estimatedStudyTimeMinutes: 420,
      difficulty: "medium",
      marksWeightage: "50%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "fr-m1-t1",
          title: "Une journée sur Terre (A Day on Earth)",
          status: "not-started",
          estimatedStudyTimeMinutes: 105,
          subtopics: [],
        },
        {
          id: "fr-m1-t2",
          title: "Une journée « écolo » (An Eco-Friendly Day)",
          status: "not-started",
          estimatedStudyTimeMinutes: 105,
          subtopics: [],
        },
        {
          id: "fr-m1-t3",
          title: "Une journée avec… (A Day With...)",
          status: "not-started",
          estimatedStudyTimeMinutes: 105,
          subtopics: [],
        },
        {
          id: "fr-m1-t4",
          title: "Une journée en Pologne (A Day in Poland)",
          status: "not-started",
          estimatedStudyTimeMinutes: 105,
          subtopics: [],
        },
      ],
    },
    {
      id: "french-module-2",
      title: "Module 2",
      description: "French culture, hospitality and education.",
      estimatedStudyTimeMinutes: 360,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "high",
      practice: [],
      topics: [
        {
          id: "fr-m2-t1",
          title: "Sortir « à la française » (Going Out the French Way)",
          status: "not-started",
          estimatedStudyTimeMinutes: 120,
          subtopics: [],
        },
        {
          id: "fr-m2-t2",
          title: "Soyez les bienvenus ! (Welcome!)",
          status: "not-started",
          estimatedStudyTimeMinutes: 120,
          subtopics: [],
        },
        {
          id: "fr-m2-t3",
          title: "Apprendre autrement (Learning Differently)",
          status: "not-started",
          estimatedStudyTimeMinutes: 120,
          subtopics: [],
        },
      ],
    },
    {
      id: "french-module-3",
      title: "Module 3",
      description: "Literature, authors and francophone culture.",
      estimatedStudyTimeMinutes: 360,
      difficulty: "medium",
      marksWeightage: "30%",
      priority: "high",
      practice: [],
      topics: [
        {
          id: "fr-m3-t1",
          title: "Jeunes talents (Young Talents)",
          status: "not-started",
          estimatedStudyTimeMinutes: 120,
          subtopics: [],
        },
        {
          id: "fr-m3-t2",
          title: "Écrivains francophones (Francophone Writers)",
          status: "not-started",
          estimatedStudyTimeMinutes: 120,
          subtopics: [],
        },
        {
          id: "fr-m3-t3",
          title: "Un livre, un jour (A Book, A Day)",
          status: "not-started",
          estimatedStudyTimeMinutes: 120,
          subtopics: [],
        },
      ],
    },
    {
      id: "french-module-4",
      title: "Module 4",
      description: "France, news and current affairs.",
      estimatedStudyTimeMinutes: 300,
      difficulty: "medium",
      marksWeightage: "30%",
      priority: "high",
      practice: [],
      topics: [
        {
          id: "fr-m4-t1",
          title: "Il a choisi la France (He Chose France)",
          status: "not-started",
          estimatedStudyTimeMinutes: 150,
          subtopics: [],
        },
        {
          id: "fr-m4-t2",
          title: "Informons-nous (Let's Stay Informed)",
          status: "not-started",
          estimatedStudyTimeMinutes: 150,
          subtopics: [],
        },
      ],
    },
  ],
};