export { cloudComputingSyllabus } from "./cloud-computing";
export { computerArchitectureSyllabus } from "./computer-architecture";
export { computerGraphicsSyllabus } from "./computer-graphics";
export { dataStructuresSyllabus } from "./data-structures";
export { dbmsSyllabus } from "./dbms";
export { dsaCodingSyllabus } from "./dsa-coding";
export { dsaTheorySyllabus } from "./dsa-theory";
export { frenchSyllabus } from "./french";
export { javaSyllabus } from "./java";
