import type { Subject } from "@/types/academic";

export const javaSyllabus: Subject = {
  id: "java",
  name: "Java Programming",
  semesterId: "semester-3",
  modules: [
    {
      id: "java-module-1",
      title: "Module 1: Java Basics",
      description:
        "Introduction to Java, Object-Oriented Programming concepts, Java syntax and programming fundamentals.",
      estimatedStudyTimeMinutes: 480,
      difficulty: "easy",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "java-m1-t1",
          title: "Concepts of Object-Oriented Programming",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m1-t1-s1",
              title: "Procedural Programming vs OOP",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t1-s2",
              title: "Basic Concepts of OOP",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m1-t2",
          title: "Features of Java",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m1-t2-s1",
              title: "Platform Independence",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t2-s2",
              title: "Robustness",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t2-s3",
              title: "Security",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t2-s4",
              title: "Multithreading",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t2-s5",
              title: "Portability",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m1-t3",
          title: "Java vs C++",
          status: "not-started",
          difficulty: "easy",
          priority: "medium",
          estimatedStudyTimeMinutes: 30,
          subtopics: [
            {
              id: "java-m1-t3-s1",
              title: "Differences between Java and C++",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m1-t4",
          title: "Java Environment Setup",
          status: "not-started",
          difficulty: "easy",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m1-t4-s1",
              title: "JDK Installation",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t4-s2",
              title: "JVM",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t4-s3",
              title: "JRE",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t4-s4",
              title: "Compiling and Running Java Programs",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m1-t5",
          title: "Basic Syntax",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m1-t5-s1",
              title: "Program Structure",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t5-s2",
              title: "Main Method",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t5-s3",
              title: "Comments",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m1-t6",
          title: "Objects and Classes",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m1-t6-s1",
              title: "Class",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t6-s2",
              title: "Object",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t6-s3",
              title: "Constructors",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m1-t7",
          title: "Data Types and Variables",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m1-t7-s1",
              title: "Primitive Data Types",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t7-s2",
              title: "Reference Data Types",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t7-s3",
              title: "Variable Types",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t7-s4",
              title: "Modifiers",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m1-t8",
          title: "Operators and Control Statements",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "java-m1-t8-s1",
              title: "Basic Operators",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t8-s2",
              title: "Decision Making",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t8-s3",
              title: "Loop Control",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m1-t9",
          title: "Strings, Arrays, Methods and I/O",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "java-m1-t9-s1",
              title: "Strings",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t9-s2",
              title: "Arrays",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t9-s3",
              title: "Methods",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m1-t9-s4",
              title: "Input / Output",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "java-module-2",
      title: "Module 2: Java Object Oriented",
      description:
        "Inheritance, polymorphism, abstraction, encapsulation, interfaces, packages and java.util package.",
      estimatedStudyTimeMinutes: 480,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "java-m2-t1",
          title: "Inheritance",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 75,
          subtopics: [
            {
              id: "java-m2-t1-s1",
              title: "Introduction to Inheritance",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t1-s2",
              title: "Types of Inheritance",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t1-s3",
              title: "super Keyword",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m2-t2",
          title: "Method Overriding",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m2-t2-s1",
              title: "Rules of Method Overriding",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t2-s2",
              title: "Runtime Polymorphism",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m2-t3",
          title: "Polymorphism",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m2-t3-s1",
              title: "Compile-Time Polymorphism",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t3-s2",
              title: "Run-Time Polymorphism",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t3-s3",
              title: "Method Overloading",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m2-t4",
          title: "Abstraction",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m2-t4-s1",
              title: "Abstract Classes",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t4-s2",
              title: "Abstract Methods",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m2-t5",
          title: "Encapsulation",
          status: "not-started",
          difficulty: "easy",
          priority: "high",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m2-t5-s1",
              title: "Data Hiding",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t5-s2",
              title: "Getter and Setter Methods",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m2-t6",
          title: "Interfaces",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m2-t6-s1",
              title: "Creating Interfaces",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t6-s2",
              title: "Implementing Interfaces",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t6-s3",
              title: "Multiple Inheritance using Interfaces",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m2-t7",
          title: "Packages",
          status: "not-started",
          difficulty: "easy",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m2-t7-s1",
              title: "Creating Packages",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t7-s2",
              title: "Importing Packages",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m2-t8",
          title: "Exploring java.util Package",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m2-t8-s1",
              title: "Collections Overview",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m2-t8-s2",
              title: "Utility Classes",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "java-module-3",
      title: "Module 3: Exception Handling and Threading",
      description:
        "Java exception handling, exception hierarchy, multithreading and thread synchronization.",
      estimatedStudyTimeMinutes: 480,
      difficulty: "hard",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "java-m3-t1",
          title: "Exception Hierarchy",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m3-t1-s1",
              title: "Throwable Class",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t1-s2",
              title: "Checked and Unchecked Exceptions",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m3-t2",
          title: "Exception Methods",
          status: "not-started",
          difficulty: "medium",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m3-t2-s1",
              title: "printStackTrace()",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t2-s2",
              title: "getMessage()",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t2-s3",
              title: "toString()",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m3-t3",
          title: "Exception Handling",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 120,
          subtopics: [
            {
              id: "java-m3-t3-s1",
              title: "try-catch Block",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t3-s2",
              title: "Multiple Catch Clauses",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t3-s3",
              title: "finally Block",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t3-s4",
              title: "Uncaught Exceptions",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t3-s5",
              title: "Java Built-in Exceptions",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m3-t4",
          title: "Introduction to Threads",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m3-t4-s1",
              title: "Creating Threads",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t4-s2",
              title: "Implementing Runnable",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t4-s3",
              title: "Extending Thread Class",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m3-t5",
          title: "Thread Management",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "java-m3-t5-s1",
              title: "Thread Priorities",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t5-s2",
              title: "Synchronization",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t5-s3",
              title: "Suspending Threads",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t5-s4",
              title: "Resuming Threads",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t5-s5",
              title: "Stopping Threads",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m3-t5-s6",
              title: "Multithreading",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "java-module-4",
      title: "Module 4: Event Handling and AWT",
      description:
        "Java Event Handling mechanism, Event Model and Abstract Window Toolkit (AWT).",
      estimatedStudyTimeMinutes: 480,
      difficulty: "medium",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "java-m4-t1",
          title: "Event Handling Mechanism",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m4-t1-s1",
              title: "Introduction to Event Handling",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t1-s2",
              title: "Delegation Event Model",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m4-t2",
          title: "Event Model",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m4-t2-s1",
              title: "Components of Event Model",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t2-s2",
              title: "Event Dispatching",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m4-t3",
          title: "Event Classes",
          status: "not-started",
          difficulty: "medium",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m4-t3-s1",
              title: "ActionEvent",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t3-s2",
              title: "MouseEvent",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t3-s3",
              title: "KeyEvent",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t3-s4",
              title: "WindowEvent",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m4-t4",
          title: "Sources of Events",
          status: "not-started",
          difficulty: "easy",
          priority: "medium",
          estimatedStudyTimeMinutes: 45,
          subtopics: [
            {
              id: "java-m4-t4-s1",
              title: "Buttons",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t4-s2",
              title: "Text Fields",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t4-s3",
              title: "Checkboxes",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m4-t5",
          title: "Event Listener Interfaces",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 60,
          subtopics: [
            {
              id: "java-m4-t5-s1",
              title: "ActionListener",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t5-s2",
              title: "MouseListener",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t5-s3",
              title: "KeyListener",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t5-s4",
              title: "WindowListener",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m4-t6",
          title: "Abstract Window Toolkit (AWT)",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 150,
          subtopics: [
            {
              id: "java-m4-t6-s1",
              title: "Working with Windows",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t6-s2",
              title: "AWT Controls",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m4-t6-s3",
              title: "Layout Managers",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    },
        {
      id: "java-module-5",
      title: "Module 5: Java Advanced",
      description:
        "Applets, Swing components and Socket Programming.",
      estimatedStudyTimeMinutes: 600,
      difficulty: "hard",
      marksWeightage: "20%",
      priority: "exam-critical",
      practice: [],
      topics: [
        {
          id: "java-m5-t1",
          title: "Applet Class",
          status: "not-started",
          difficulty: "medium",
          priority: "high",
          estimatedStudyTimeMinutes: 90,
          subtopics: [
            {
              id: "java-m5-t1-s1",
              title: "Applet Class",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t1-s2",
              title: "Applet Architecture",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t1-s3",
              title: "Applet Skeleton",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t1-s4",
              title: "Display Methods",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m5-t2",
          title: "Swing",
          status: "not-started",
          difficulty: "medium",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 180,
          subtopics: [
            {
              id: "java-m5-t2-s1",
              title: "JApplet",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t2-s2",
              title: "Icons",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t2-s3",
              title: "Labels",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t2-s4",
              title: "Text Fields",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t2-s5",
              title: "Buttons",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t2-s6",
              title: "Combo Boxes",
              status: "not-started",
              resources: [],
            },
          ],
        },
        {
          id: "java-m5-t3",
          title: "Socket Programming",
          status: "not-started",
          difficulty: "hard",
          priority: "exam-critical",
          estimatedStudyTimeMinutes: 210,
          subtopics: [
            {
              id: "java-m5-t3-s1",
              title: "Introduction to Socket Programming",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t3-s2",
              title: "Socket Methods",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t3-s3",
              title: "ServerSocket Methods",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t3-s4",
              title: "Socket Client Example",
              status: "not-started",
              resources: [],
            },
            {
              id: "java-m5-t3-s5",
              title: "Socket Server Example",
              status: "not-started",
              resources: [],
            },
          ],
        },
      ],
    }
  ],
};